### PR TITLE
Build native part on install with cmake-js

### PR DESCRIPTION
**Pull request by Robinlemon**
## Changes

Builds C++ sources using CMake, invoked through `cmake-js`. This requires path changes in ConfusableMatcher to accommodate cwd.

### CODE REVIEW

**Comment by Robinlemon** [comment]
Blocked by https://github.com/TETYYS/ConfusableMatcher/pull/3

**Comment by Robinlemon** [comment]
To try out my fork of CM with the new CMake file:
```
sed -i 's/TETYYS/Robinlemon/' .gitmodules
git submodule sync
yarn clean
yarn install
yarn test
```

**Comment by Robinlemon** [comment]
Would be nice to not build any of the test files. CMake adjustments for CM would be required. If cutting all tests out, package is 2MB unpacked, currently at 6MB.

**Comment by Robinlemon** [comment]
If you want to try installing the package:
```
npm pack
cd ..
mkdir cm-js-test
cd cm-js-test
npm init -y
npm i ../ConfusableMatcher-js-interop/confusablematcher-js-interop-2.0.1.tgz
```

**Comment by TETYYS** [comment]
🆒

**Pull request merged**
